services:
  - type: web
    name: anime_blog
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: |
      bash -c "python manage.py migrate --noinput && gunicorn anime_blog.wsgi"