services:
  - type: web
    name: anime-blog
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn anime_blog.wsgi --log-file -