services:
  - type: web
    name: anime_blog
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn anime_blog.wsgi"
    postDeployCommand: "python manage.py migrate"